version: 2
updates:
- package-ecosystem: "npm"
  # Files stored in `/` directory
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "04:00"
  open-pull-requests-limit: 5
  target-branch: "feature/deps"
  reviewers: 
    - o-w-o
- package-ecosystem: npm
  directory: "/packages/@o-w-o"
  schedule:
    interval: "monthly"
    time: "04:00"
  open-pull-requests-limit: 5
  target-branch: "feature/deps"
  reviewers: 
    - o-w-o
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: "daily"
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: "feature/deps"
  reviewers: 
    - o-w-o
  
- package-ecosystem: "github-actions"
  # Workflow files stored in the
  # default location of `.github/workflows`
  directory: ".github/workflows"
  schedule:
    interval: "daily"
    time: "04:00"
  target-branch: "feature/workflows"
  reviewers: 
    - o-w-o
