version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 10
    target-branch: "feature/deps"
    reviewers:
      - o-w-o

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    target-branch: "feature/workflows"
    open-pull-requests-limit: 10
    reviewers:
      - o-w-o
